### ISSUE TITLE
Расскажите, пожалуйтса про название class или id через запятую для отключение.

### ISSUE THREAD

**Issue by alexd73** [veks/button-visually-impaired-wordpress#1]
Добрый день! Что это за настройка?
> Впишите  название class или id через запятую для отключение при включении версии для слабовидящих.

Спасибо!

**Comment by veks** [comment]
Здравствуйте, к примеру вам нужно скрыть какой то класс или ид при включении режима для слабовидящих, то в поле пишите название которое нужно вам скрыть.
