### ISSUE TITLE
Как убрать текст рядом с кнопкой

### ISSUE THREAD

**Issue by mongugay** [veks/button-visually-impaired-wordpress#2]
После включения плагина, рядом с кнопкой которая отображается на сайте пишется текст "Версия для слабовидящих" Как можно убрать этот текст, чтобы осталась только кнопка ?

https://yadi.sk/i/UvBrT8JI3NwFmk

**Comment by veks** [comment]
Адрес сайта напишите я посмотрю что в коде.
