### ISSUE TITLE
Обращение к несуществующему атрибуту.

### ISSUE THREAD

**Issue by Termvsrobo** [veks/button-visually-impaired-wordpress#3]
https://github.com/veks/button-visually-impaired-wordpress/blob/d858e8eb21e77684bc2f37a88f5a3095d36e3320/Button-visually-impaired.php#L521

Тут видимо копипаст, но в этом классе не описан атрибут get_option, так как класс не наследуется от **bvi_isvek**. У себя пофиксил в конструкторе как [тут](https://github.com/veks/button-visually-impaired-wordpress/blob/d858e8eb21e77684bc2f37a88f5a3095d36e3320/Button-visually-impaired.php#L35)

**Comment by veks** [comment]
В новом обновлении исправлено.

**Comment by veks** [comment]
Исправлено в новой версии
